version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\makii42\gottaw
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install: 
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u -v github.com/golang/mock/gomock
  - go get -u -v github.com/golang/mock/mockgen
  - go get -u -v github.com/Masterminds/glide
  - go get -u -v github.com/golang/dep/cmd/dep
  - dep ensure
  - go generate ./config/... ./daemon/... ./defaults/... ./docker/... ./output/... ./pipeline/... ./watch/... . 

test_script: 
  - go test -v -cover ./config/... ./daemon/... ./defaults/... ./docker/... ./output/... ./pipeline/... ./watch/... . 
  - go build -v .
  - gottaw.exe defaults
