version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\makii42\gottaw
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install: 
  - go version
  - go env
  - go get github.com/golang/mock/gomock
  - go get github.com/golang/mock/mockgen
  - go get github.com/Masterminds/glide
  - glide i -v
  # no subshell on windows, is there?
  - go generate ./config/... ./daemon/... ./defaults/... ./docker/... ./output/... ./pipeline/... ./watch/... . 

test_script: 
  # no subshell on windows, is there? 
  # Check it out at https://stackoverflow.com/questions/434038/whats-the-cmd-powershell-equivalent-of-back-tick-on-bash
  # Not sure if appveyor runs powershell
  - go test -v -cover ./config/... ./daemon/... ./defaults/... ./docker/... ./output/... ./pipeline/... ./watch/... . 
  - go build -v .
  - gottaw.exe defaults
