version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\makii42\gottaw
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install: 
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/golang/mock/gomock
  - go get github.com/golang/mock/mockgen
  - go get github.com/Masterminds/glide
  - go get github.com/golang/dep
  - dep ensure
  - go generate $(glide novendor)

test_script: 
  - go test -v -cover $(glide novendor)
  - go build -v .
  - gottaw.exe defaults
