# This one only runs locally
workspace:
  base: /go
  path: src/github.com/makii42/gottaw

pipeline:
  build:
    image: golang:1.9
    commands: 
      - go get -u -v github.com/golang/mock/gomock
      - go get -u -v github.com/golang/mock/mockgen
      - go get -u -v github.com/golang/dep/cmd/dep
      - go get -u -v github.com/Masterminds/glide
      - dep ensure
      - go generate ./...
      - go test -cover $(glide novendor)
      - go build -v .
      - ./gottaw defaults
