# This one only runs locally
workspace:
  base: /go
  path: src/github.com/makii42/gottaw

pipeline:
  build:
    image: golang:1.14
    commands: 
      - go get -u -v github.com/golang/mock/gomock
      - go get -u -v github.com/golang/mock/mockgen
      - dep ensure
      - go generate ./...
      - go test -cover ./...
      - go build -v 
      - ./gottaw defaults
