# What is this file? Check it out at https://github.com/makii42/gottaw !
growl: true
excludes:
  - gottaw*
  - .git
  - .vscode
  - .gitrecinfo
  - .wercker
pipeline: 
  - go get -v .
  - go build -v .
  - go test -cover ./...
  - go install
