excludes:
  - gottaw
  - .git
  - .git/*
  - .git/*/*
  - .git/*/*/*
  - .git/*/*/*/*
  - .vscode
  - .vscode/*
  - .gitrecinfo
  - gottaw-go-tmp-umask
pipeline: 
  - go build -v .
  - go test -v ./... 
  - go install
