# What is this file? Check it out at https://github.com/makii42/gottaw !
growl: true
excludes:
  - gottaw*
  - .git
  - .idea
  - .vscode
  - vendor
  - .gitrecinfo
  - .wercker
  - mocks
  - "*/*_mocks.go"
  - "*___jb_tmp___"
  - "*___jb_old___"
pipeline:
  - glide i -v
  - go generate $(glide novendor)
  - go test -cover $(glide novendor)
  - go build .
