# What is this file? Check it out at https://github.com/makii42/gottaw !
growl: true
excludes:
  - gottaw*
  - .git
  - .idea
  - .vscode
  - .gitrecinfo
  - .wercker
  - "*___jb_tmp___"
  - "*___jb_old___"
pipeline:
  - go get -t -v ./...
  - go build -v .
  - go test -cover ./...
  - go build .
