language: go
go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
os: 
  - linux
before_install:
  - go get -u github.com/golang/mock/gomock
  - go get -u github.com/golang/mock/mockgen
  - go get -u github.com/mattn/goveralls
before_script: 
  - go generate ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
