language: go
sudo: false
go:
  #- 1.5.x
  #- 1.6.x
  - 1.7.x
  - 1.8.x
  - master
os: 
  - linux
  - osx
before_install:
  - go get github.com/golang/mock/gomock
  - go get github.com/golang/mock/mockgen
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
install: 
  - glide install --strip-vendor
before_script: 
  - go generate $(glide novendor)
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci