language: go
sudo: false
go:
  - 1.8.x
  - 1.9
  - master
os: 
  - linux
  - osx
before_install:
  - go get -u -v github.com/golang/mock/gomock
  - go get -u -v github.com/golang/mock/mockgen
  - go get -u -v github.com/Masterminds/glide
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v github.com/golang/dep/cmd/dep
install: 
  - dep ensure
before_script: 
  - go generate $(glide novendor)
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci